[package]
name = "rust-01-baisc"
version = "0.1.0"
edition = "2024"

[dependencies]
negative-impl = "0.1.4"
tokio = { version = "1.46.1", features = ["rt", "rt-multi-thread", "macros", "time"] }
regex = "1.11.1"